"use client";

import { useEffect, useState } from "react";
import { Sparkles, Loader2, TrendingDown, TrendingUp, Minus } from "lucide-react";
import { Card, Button, Badge, LoadingBlock, EmptyState } from "@/components/ui/Primitives";
import { api, ApiError } from "@/lib/api-client";
import { formatDate } from "@/lib/utils";

const STATUS_TONE: Record<string, "neutral" | "success" | "warning" | "danger" | "info"> = {
  New: "info",
  "Under Review": "warning",
  Accepted: "success",
  Rejected: "danger",
  Implemented: "success",
};

const IMPACT_ICON: Record<string, any> = {
  decrease: TrendingDown,
  increase: TrendingUp,
  neutral: Minus,
  unknown: Minus,
};

export default function RecommendationsPage() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [notConfigured, setNotConfigured] = useState(false);
  const [updatingId, setUpdatingId] = useState<string | null>(null);

  function load() {
    setLoading(true);
    api
      .get<any[]>("/api/v1/recommendations")
      .then(setItems)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }

  useEffect(load, []);

  async function handleGenerate() {
    setGenerating(true);
    setError(null);
    setNotConfigured(false);
    try {
      const created = await api.post<any[]>("/api/v1/recommendations");
      setItems((prev) => [...created, ...prev]);
    } catch (err) {
      if (err instanceof ApiError && err.message === "AI service not configured") {
        setNotConfigured(true);
      } else {
        setError(err instanceof ApiError ? err.message : "Could not generate recommendations.");
      }
    } finally {
      setGenerating(false);
    }
  }

  async function updateStatus(id: string, status: string) {
    setUpdatingId(id);
    try {
      const updated = await api.patch<any>(`/api/v1/recommendations/${id}`, { status });
      setItems((prev) => prev.map((r) => (r.id === id ? updated : r)));
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Could not update recommendation.");
    } finally {
      setUpdatingId(null);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold text-charcoal-900">Recommendations</h1>
          <p className="text-sm text-charcoal-500">
            Evidence-grounded recommendations generated by IBM Granite from your ML analytics and reference corpus.
          </p>
        </div>
        <Button onClick={handleGenerate} disabled={generating}>
          {generating ? <Loader2 size={15} className="animate-spin" /> : <Sparkles size={15} />}
          Generate AI Recommendation
        </Button>
      </div>

      {notConfigured && (
        <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          AI service not configured. Set GRANITE_API_KEY, GRANITE_PROJECT_ID, GRANITE_API_URL and GRANITE_MODEL
          environment variables to enable AI-generated recommendations.
        </div>
      )}
      {error && <div className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}

      {loading && <LoadingBlock label="Generating AI recommendation..." />}

      {!loading && items.length === 0 && !error && (
        <EmptyState
          title="No recommendations yet."
          description="Click 'Generate AI Recommendation' after uploading waste data to get evidence-grounded suggestions."
        />
      )}

      <div className="grid gap-4">
        {items.map((r) => {
          const Icon = IMPACT_ICON[r.expectedImpactDirection] ?? Minus;
          return (
            <Card key={r.id} className="space-y-3">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <Badge tone={r.priority === "Critical" || r.priority === "High" ? "danger" : r.priority === "Medium" ? "warning" : "neutral"}>
                    {r.priority} priority
                  </Badge>
                  {r.category && <Badge tone="neutral">{r.category}</Badge>}
                  <Badge tone={STATUS_TONE[r.status] ?? "neutral"}>{r.status}</Badge>
                </div>
                <p className="text-xs text-charcoal-400">{formatDate(r.createdAt?.slice(0, 10) ?? "")}</p>
              </div>

              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-charcoal-400">Finding</p>
                <p className="text-sm text-charcoal-800">{r.finding}</p>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-charcoal-400">Evidence</p>
                <p className="text-sm text-charcoal-600">{r.evidence}</p>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-charcoal-400">Recommendation</p>
                <p className="text-sm font-medium text-forest-800">{r.recommendationText}</p>
              </div>

              <div className="flex flex-wrap items-center gap-4 text-xs text-charcoal-500">
                <span className="flex items-center gap-1">
                  <Icon size={13} /> Expected impact: {r.expectedImpactDirection}
                </span>
                <span>Confidence: {r.confidence}</span>
                <span>Source: {r.source}</span>
              </div>
              {r.limitations && <p className="text-xs italic text-charcoal-400">Limitations: {r.limitations}</p>}

              <div className="flex flex-wrap gap-2 border-t border-forest-100 pt-3">
                {["Under Review", "Accepted", "Rejected", "Implemented"].map((s) => (
                  <Button
                    key={s}
                    variant={r.status === s ? "primary" : "secondary"}
                    disabled={updatingId === r.id}
                    onClick={() => updateStatus(r.id, s)}
                    className="!px-3 !py-1.5 text-xs"
                  >
                    {s}
                  </Button>
                ))}
              </div>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
